name: Classroom Platform CI/CD

on:
  push:
    branches: [ "master", "staging" ]
  pull_request:
    branches: [ "master" ]

env:
  TF_VERSION: 1.5.0
  WORKING_DIR: . 

jobs:
  terraform-validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform Init
        run: terraform -chdir=${{ env.WORKING_DIR }} init -backend-config=backend.hcl -input=false
        env:
            ARM_CLIENT_ID: ${{ fromJson(secrets.AZURE_CREDENTIALS).clientId }}
            ARM_CLIENT_SECRET: ${{ fromJson(secrets.AZURE_CREDENTIALS).clientSecret }}
            ARM_SUBSCRIPTION_ID: ${{ fromJson(secrets.AZURE_CREDENTIALS).subscriptionId }}
            ARM_TENANT_ID: ${{ fromJson(secrets.AZURE_CREDENTIALS).tenantId }}
    
      - name: Terraform Validate
        run: terraform -chdir=${{ env.WORKING_DIR }} validate

  deploy-staging:
    runs-on: ubuntu-latest
    needs: terraform-validate
    steps:
      - uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform Plan (staging)
        run: terraform -chdir=${{ env.WORKING_DIR }} plan -out=tfplan -var="env=staging"
        env:
            ARM_CLIENT_ID: ${{ fromJson(secrets.AZURE_CREDENTIALS).clientId }}
            ARM_CLIENT_SECRET: ${{ fromJson(secrets.AZURE_CREDENTIALS).clientSecret }}
            ARM_SUBSCRIPTION_ID: ${{ fromJson(secrets.AZURE_CREDENTIALS).subscriptionId }}
            ARM_TENANT_ID: ${{ fromJson(secrets.AZURE_CREDENTIALS).te
            
      - name: Terraform Apply (staging)
        run: terraform -chdir=${{ env.WORKING_DIR }} apply -auto-approve tfplan
        env:
            ARM_CLIENT_ID: ${{ fromJson(secrets.AZURE_CREDENTIALS).clientId }}
            ARM_CLIENT_SECRET: ${{ fromJson(secrets.AZURE_CREDENTIALS).clientSecret }}
            ARM_SUBSCRIPTION_ID: ${{ fromJson(secrets.AZURE_CREDENTIALS).subscriptionId }}
            ARM_TENANT_ID: ${{ fromJson(secrets.AZURE_CREDENTIALS).te
            
  deploy-prod:
    runs-on: ubuntu-latest
    needs: deploy-staging
    environment: production   
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform Plan (prod)
        run: terraform -chdir=${{ env.WORKING_DIR }} plan -out=tfplan-prod -var="env=prod"

      - name: Terraform Apply (prod)
        run: terraform -chdir=${{ env.WORKING_DIR }} apply -auto-approve tfplan-prod
